import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { SessionWrapper } from "@/components/SessionWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <SessionWrapper>
        <body className={`${inter.className} antialiased`}>
          {children}
        </body>
      </SessionWrapper>
    </html>
  );
}
